---
##############################################################
#
# Namespace
#
##############################################################
apiVersion: v1
kind: Namespace
metadata:
  {{#json2yaml "this"}}{{/json2yaml}}
---